# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :dnsserver do |dnsserver|
    dnsserver.vm.box = "precise32"
    dnsserver.vm.network :private_network, ip: "10.11.1.100"
  end

  config.vm.define :asteriskpbx do |asteriskpbx|
    asteriskpbx.vm.box = "precise32"
    asteriskpbx.vm.network :private_network, ip: "10.11.1.101"
  end
end
